# Generated by Django 4.0 on 2021-12-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yapp', '0002_rename_donor_book_reader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date_hired',
            new_name='date_barrowed',
        ),
    ]
