# Generated by Django 4.0 on 2021-12-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yapp', '0003_rename_date_hired_book_date_barrowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reader',
            new_name='donor',
        ),
    ]
