# Generated by Django 4.0 on 2021-12-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yapp', '0004_rename_reader_book_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='booknumber',
        ),
    ]
